#!/usr/bin/env python3

CONDITION_CODES = {
            200: {"owm":"thunderstorm with light rain", "snips":["de l'orage et un peu de pluie", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            201: {"owm":"thunderstorm with rain", "snips":["de l'orage et de la pluie", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            202: {"owm":"thunderstorm with heavy rain", "snips":["de l'orage et des grosses averses", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            210: {"owm":"light thunderstorm", "snips":["des petits orages", "éclairs", "tonnerre", "orageux", "orage"]},
            211: {"owm":"thunderstorm", "snips":["des orages", "éclairs", "tonnerre", "orageux", "orage"]},
            212: {"owm":"heavy thunderstorm", "snips":["de gros orages", "éclairs", "tonnerre", "orageux", "orage"]},
            221: {"owm":"ragged thunderstorm", "snips":["des orages irréguliers", "éclairs", "tonnerre", "orageux", "orage"]},
            230: {"owm":"thunderstorm with light drizzle", "snips":["des orages et une légère bruine", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie", 
"tempête"]},
            231: {"owm":"thunderstorm with drizzle", "snips":["des orages et de la bruine", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie", "tempête"]}
,
            232: {"owm":"thunderstorm with heavy drizzle", "snips":["des orages et de la grosse bruine", "pleuvoir", "éclairs", "tonnerre", "orageux", "orage", "dépression", "humide", "gris", "pluvieux", "pluie"
, "tempête"]},
            300: {"owm":"light intensity drizzle", "snips":["une petite bruine", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            301: {"owm":"drizzle", "snips":["de la bruine", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            302: {"owm":"heavy intensity drizzle", "snips":["de la grosse bruine", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            310: {"owm":"light intensity drizzle rain", "snips":["de la pluie de faible intensité", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            311: {"owm":"drizzle rain", "snips":["de la pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            312: {"owm":"heavy intensity drizzle rain", "snips":["de la grosse pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie", "tempête"]},
            313: {"owm":"shower rain and drizzle", "snips":["des averses de pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            314: {"owm":"heavy shower rain and drizzle", "snips":["des grosses averses de pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            321: {"owm":"shower drizzle", "snips":["des averses de bruine", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            500: {"owm":"light rain", "snips":["une légère pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            501: {"owm":"moderate rain", "snips":["des précipitations modérées", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            502: {"owm":"heavy intensity rain", "snips":["de la grosse pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            503: {"owm":"very heavy rain", "snips":["de l'énorme pluie", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie", "tempête"]},
            504: {"owm":"extreme rain", "snips":["le déluge", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie", "tempête"]},
            511: {"owm":"freezing rain", "snips":["de la pluie verglaçante", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            520: {"owm":"light intensity shower rain", "snips":["des petites averses", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            521: {"owm":"shower rain", "snips":["des averses", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            522: {"owm":"heavy intensity shower rain", "snips":["des grosses averses", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie", "tempête"]},
            531: {"owm":"ragged shower rain", "snips":["des averses éparses", "pleuvoir", "dépression", "humide", "gris", "pluvieux", "pluie"]},
            600: {"owm":"light snow", "snips":["un peu de neige", "chutes de neige", "dépression", "enneigé", "neige"]},
            601: {"owm":"Snow", "snips":["de la neige", "chutes de neige", "dépression", "enneigé", "neige"]},
            602: {"owm":"Heavy snow", "snips":["beaucoup de neige", "tempête de neige", "chutes de neige", "dépression", "enneigé", "neige", "tempête"]},
            611: {"owm":"Sleet", "snips":["de la neige fondue", "chutes de neige", "dépression", "enneigé", "neige"]},
            612: {"owm":"Light shower sleet", "snips":["des petites averses de neige fondue", "chutes de neige", "dépression", "enneigé", "neige"]},
            613: {"owm":"Shower sleet", "snips":["des averses de neige fondue", "chutes de neige", "dépression", "enneigé", "neige", "humide", "gris", "pluvieux", "pluie"]},
            615: {"owm":"Light rain and snow", "snips":["un peu de pluie et neige mélées", "pleuvoir", "chutes de neige", "dépression", "enneigé", "neige", "humide", "gris", "pluvieux", "pluie"]},
            616: {"owm":"Rain and snow", "snips":["de la pluie et neige mélées", "pleuvoir", "chutes de neige", "dépression", "enneigé", "neige", "humide", "gris", "pluvieux", "pluie"]},
            620: {"owm":"Light shower snow", "snips":["des petites averses de neige", "chutes de neige", "dépression", "enneigé", "neige"]},
            621: {"owm":"Shower snow", "snips":["des averses de neige", "chutes de neige", "dépression", "enneigé", "neige"]},
            621: {"owm":"Heavy shower snow", "snips":["des grosses averses de neige", "tempête de neige", "chutes de neige", "dépression", "enneigé", "neige", "tempête"]},
            701: {"owm":"mist", "snips":["de la brume", "brûme", "gris", "humide"]},
            711: {"owm":"Smoke", "snips":["de la fumée"]},
            721: {"owm":"Haze", "snips":["de la brume", "brûme", "gris", "humide"]},
            731: {"owm":"sand/ dust whirls", "snips":["des tourbillons de sable"]},
            741: {"owm":"fog", "snips":["du brouilard", "brouillard", "gris", "humide"]},
            751: {"owm":"sand", "snips":["du sable"]},
            761: {"owm":"dust", "snips":["de la poussière"]},
            762: {"owm":"volcanic ash", "snips":["de la cendre volcanique"]},
            771: {"owm":"squalls", "snips":["des rafales de vent"]},
            781: {"owm":"tornado", "snips":["des tornades", "cyclone"]},
            800: {"owm":"clear sky", "snips":["du soleil", "soleil", "ensoleillé", "anti-cyclone"]},
            801: {"owm":"few clouds: 11-25%", "snips":["quelques nuages", "nuageux", "nuage"]},
            802: {"owm":"scattered clouds: 25-50%", "snips":["des nuages épars", "nuageux", "nuage"]},
            803: {"owm":"broken clouds: 51-84%", "snips":["pas mal de nuages", "nuageux", "nuage", "gris", "couvert"]},
            804: {"owm":"overcast clouds: 85-100%", "snips":["un ciel couvert", "nuageux", "nuage", "gris", "couvert"]},
}

